
import React from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { ABTest } from "@/hooks/useMockABTestData";
import { Skeleton } from "@/components/ui/skeleton";
import { HelpCircle, FileQuestion, Calculator, Lightbulb } from "lucide-react";
import { Separator } from "@/components/ui/separator";

interface ContextTabProps {
  test: ABTest;
  loading: boolean;
}

export function ContextTab({ test, loading }: ContextTabProps) {
  if (loading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-[150px] w-full" />
        <Skeleton className="h-[150px] w-full" />
        <Skeleton className="h-[150px] w-full" />
        <Skeleton className="h-[200px] w-full" />
      </div>
    );
  }
  
  // Define context data
  // In a real application, this would come from the API
  const contextData = {
    learningAgenda: {
      team: test.channel === "Social Media" ? "Performance Marketing Team" : 
             test.channel === "Email" ? "CRM Team" : "Brand Marketing Team",
      objective: test.description || "To understand the incremental impact of marketing activities"
    },
    businessQuestion: test.hypothesis || "What is the true incremental value generated by our marketing spend?",
    methodologyReason: "Incrementality Testing was selected because it provides a direct measurement of causal impact through controlled experimentation, which is more accurate than correlation-based methods like MMM or path-based attribution like MTA.",
    results: {
      summary: test.analysis || "The test demonstrated a significant positive impact on conversion rates and ROAS",
      implications: test.nextSteps || "Results suggest increasing investment in the tested channel would be beneficial",
      nextSteps: "Implement the winning approach across all relevant marketing activities"
    }
  };

  return (
    <div className="space-y-6">
      {/* Learning Agenda */}
      <Card className="glass-card premium-shadow border-white/30">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2">
            <HelpCircle className="h-5 w-5 text-primary" />
            Learning Agenda
          </CardTitle>
          <CardDescription>
            Team responsible and testing objective
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="bg-muted/50 p-4 rounded-md">
              <p className="mb-2"><span className="font-medium">Proposing Team:</span> {contextData.learningAgenda.team}</p>
              <p><span className="font-medium">Testing Objective:</span> {contextData.learningAgenda.objective}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Business Question */}
      <Card className="glass-card premium-shadow border-white/30">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2">
            <FileQuestion className="h-5 w-5 text-primary" />
            Business Question
          </CardTitle>
          <CardDescription>
            The key question this test aimed to answer
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="bg-purple-50/80 backdrop-blur-sm p-4 rounded-lg border border-purple-100 premium-shadow">
            <p className="text-purple-800 italic">"{contextData.businessQuestion}"</p>
          </div>
        </CardContent>
      </Card>

      {/* Methodology Selection */}
      <Card className="glass-card premium-shadow border-white/30">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2">
            <Calculator className="h-5 w-5 text-primary" />
            Methodology Selection
          </CardTitle>
          <CardDescription>
            Why incrementality testing was chosen over other approaches
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="bg-muted/50 p-4 rounded-md">
              <p>{contextData.methodologyReason}</p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-4">
              <div className="p-3 border rounded-md">
                <p className="font-medium mb-1">Incrementality Testing</p>
                <p className="text-sm text-muted-foreground">Direct causal measurement through controlled experimentation</p>
              </div>
              <div className="p-3 border rounded-md bg-muted/20">
                <p className="font-medium mb-1">Marketing Mix Modeling</p>
                <p className="text-sm text-muted-foreground">Statistical analysis of historical data to estimate channel contributions</p>
              </div>
              <div className="p-3 border rounded-md bg-muted/20">
                <p className="font-medium mb-1">Multi-Touch Attribution</p>
                <p className="text-sm text-muted-foreground">Path-based credit assignment for customer journey touchpoints</p>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Final Results & Implications */}
      <Card className="glass-card premium-shadow border-white/30">
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-primary" />
            Final Results & Implications
          </CardTitle>
          <CardDescription>
            Key findings and business impact
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-medium mb-2">Summary of Findings</h3>
              <p className="text-muted-foreground">{contextData.results.summary}</p>
            </div>
            
            <Separator className="bg-white/20" />
            
            <div>
              <h3 className="text-lg font-medium mb-2">Business Implications</h3>
              <p className="text-muted-foreground">{contextData.results.implications}</p>
            </div>
            
            <Separator className="bg-white/20" />
            
            <div className="bg-green-50/80 backdrop-blur-sm p-4 rounded-lg border border-green-100 premium-shadow">
              <h3 className="text-lg font-medium text-green-800 mb-2">Recommended Next Steps</h3>
              <p className="text-green-700">{contextData.results.nextSteps}</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
